#!/bin/sh

PROGNAME=$(basename "$0")
LOCKFILE_DIR=/var/lock
LOCK_FD=200
LOCK_SLEEP_USECS=333333
LOCK_SLEEP_PERIODS=15

lock() {
  local prefix=$1
  local fd=${2:-$LOCK_FD}
  local lock_file=$LOCKFILE_DIR/$prefix.lock
  local i=0

  # create lock file
  eval "exec $fd>$lock_file"

  # acquire the lock
  while ! flock -x -n $fd; do
    i=$((i+1))
    if [ $i -gt $LOCK_SLEEP_PERIODS ]; then
      return 1
    fi
    usleep $LOCK_SLEEP_USECS
  done
  return 0
}

lock $PROGNAME || exit 1

if [ "x$1" = "x--init" ]; then
	shift
	# Comm setup
	i2cset -y 3 0x3e 0x00 0x38 b

	# Select IS=1
	i2cset -y 3 0x3e 0x00 0x39 b

	# Configure display to reset state
	i2cset -y 3 0x3e 0x00 0x17 0x78 0x5e 0x6d 0x0c 0x01 0x06 i

	# Clear display
	i2cset -y 3 0x3e 0x00 0x01

	# KnCMiner
	i2cset -y 3 0x3e 0x40 0x4b 0x6e 0x43 0x4d 0x69 0x6e 0x65 0x72 i
fi

if [ $# = 0 ]; then
	exit 0
fi

line=1
if [ "x$1" = "x-l" ]; then
	line=$2
	shift
	shift
fi

i2cset -y 3 0x3e 0x00 $((line * 40 - 40 + 0x80))
text="`echo "$@                                        " | cut -c-40`"
while [ "$text" != "" ]; do
	frag="`echo "$text" | cut -c-30`"
	text="`echo "$text" | cut -c31-`"
	i2cset -y 3 0x3e 0x40 `echo -n "$frag" | hexdump -v -e '/1 "%u "'` i
done
