#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
LOG_FILE="/var/log/monitordcdc.log"

fail=0
while true ; do
  sleep 30

  if i2cget -f -y 0 0x70 >/dev/null 2>/dev/null ; then
    fail=0
  else
    fail=$((fail+1))
    echo [$(date +"%F %T")] I2C lock failure '#'$fail >> $LOG_FILE
  fi

  if [[ $fail -ge 3 ]]; then
    echo [$(date +"%F %T")] Rebooting due to I2C lock >> $LOG_FILE
    reboot
  fi
done
