#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

while true ; do
  sleep 1
  if [ ! -f /config/cgminer.conf ]; then
    continue
  fi

  lcd-message $(cat /etc/knc-release)
  sleep 1
  MHS=$(/home/pi/bfgminer/bfgminer-rpc | sed -n -e 's/^.*\[MHS 20s\][^0123456789]\+\([0123456789]\+\).*$/\1/p')
  if [ "x$MHS" = "x" ]; then
    lcd-message "0 MHs"
  else
    lcd-message "$MHS MHs"
  fi
done
